### PR TITLE
address warning and do something extra rather silently run

### PR DESCRIPTION
**Pull request by netskink**

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Can you add some text explaining what enhancements and/or problems this is addressing?

**Comment by netskink** [comment]
It removes a warning and it prints some output rather than silently running per your TODO issue.

**Comment by netskink** [comment]
Addresses this [issue](https://github.com/ZOSOpenTools/zotsampleport/issues/4) by printing the result, so it no longer runs silently. 

Also, the build requires a tarball url.  As it is now, it it uses my fork as the source of the pull request since the target exists there.  I propose once this pull request is accepted, I do a followup to change the location of the pull.  I suggest we do this in this order because until the pull request is merged, the build will fail since the new tarball is not in the zot repo.

**Review by MikeFultonDev — APPROVED** [review]
Thanks Lgtm

**Comment by netskink** [comment]
You are welcome and thanks.  Once its merged, I'll do the followup on the tarball location change.

**Pull request merged**
